### ISSUE TITLE
vim support

### ISSUE THREAD

**Issue by jabbalaci** [timothycrosley/deprecated.frosted#26]
How could I integrate it in vim? Could you write about it too? It would be nice if the solution were vundle-ready.

Thanks,

Laszlo

**Comment by timothycrosley** [comment]
Hi Laszlo,

Thanks for noting this! Integration with text-editors and other tools is certainly a priority for the project. There is not currently a vim plugin - and since I do not actively use vim I can't comment on how it might be used without a plugin from within the editor. I'll be reaching out to my more vim proficient friends to try to rectify this, and update this bug when the situation changes.

Thanks!

Timothy

**Comment by lcd047** [comment]
@jabbalaci Please take a look at [syntastic](https://github.com/scrooloose/syntastic).  It's a general feramework for interfacing Vim with various syntax checkers.  Right now it supports 137 checkers, for 79 filetypes.  I just added support for frosted.

**Comment by timothycrosley** [comment]
@lcd047 that's pretty cool! Will add a note about syntastic integration in the readme

**Comment by timothycrosley** [comment]
Closing this issue as vim support has been added via syntastic, and is now linked to in README

Thanks!

Timothy
