### ISSUE TITLE
Question: why skipping __init__.py by default?

### ISSUE THREAD

**Issue by aelgru** [timothycrosley/deprecated.frosted#29]
The production code of one of my projects consists of only one `__init__.py` file right now. I don't understand why `frosted` ignores `__init__.py` by [default](https://github.com/timothycrosley/frosted/blob/develop/frosted/settings.py#L40).

**Comment by timothycrosley** [comment]
@aelgru, the reason it ignores **init**.py is because generally this file is "special" often importing stuff without using it for the propose of exposing an API. That said, I agree this isn't ideal. Ill update frosted in the next release to include **init**.py but to ignore unused imports within this file by default.

Thanks!

Timothy

**Comment by timothycrosley** [comment]
Fixed in release 1.3.0

Thanks!

~Timothy
