### ISSUE TITLE
do not show W101 (bare except used) if exception reraises

### ISSUE THREAD

**Issue by Shura1oplot** [timothycrosley/deprecated.frosted#48]
Warning W101 is not needed if exception reraises.

```
try:
    something
except:
    logging.exception("something raises exception", *sys.exc_info())
    raise
```

**Comment by timothycrosley** [comment]
Hi @Shura1oplot,

Thanks for reporting this issue - I agree and will try to implement a fix before the next release.

~Tim

**Comment by rsyring** [comment]
FWIW, I would argue you still want to warn against this.  A bare accept is not recommended per the python docs:

https://docs.python.org/2/howto/doanddont.html#except

It's very unlikely that you would want a bar except.  Instead, you IMO should be using "except Exception".  

Therefore, this warning still seems valid to me.  If if you are reraising it, the warning should still be there to make you ask, "Do I really need a bare except here?"

Since it should be very rare to answer that question with a "yes", I'd say leave the warning and if you really need to supress it, use the # noqa.

Just my $0.02.

**Comment by timothycrosley** [comment]
Hi @rsyring,

Thanks for the input, after thinking it over I'm with you on this. Especially now that frosted supports # noqa comments - so if you are 100% sure you want to ignore this error it is easily doable. Additionally the logic for checking for a reraise would be very error-prone, should we  ignore it if the reraise is in a conditional? What if the conditional always is True? I think in this case it's better to force explicitly, then try to determine the developers intent.

Thanks!

~Timothy
